version: "3.8"
services:

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.18
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"

  collector:
    container_name: collector
    image: dev/otel/collector:default
    volumes:
      - "//e/open-telemetry/docker/otel/collector/otel-config.yaml:/etc/otel/config.yaml"
    ports:
      - "9464:9464"
      - "55678:55678"
      - "55679:55679"
      - "55680:55680"
      - "55681:55681"
    depends_on:
      - zipkin
      - jaeger

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - collector
